/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop.x.pertemuan10;

import static oop.x.pertemuan10.dbkoneksi.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author defrasuhadi
 * TGL: 24 mei 2025
 */
public class fMahasiswa extends javax.swing.JFrame {
    DefaultTableModel dtm = new DefaultTableModel();
    /**
     * Creates new form fMahasiswa
     * @throws java.sql.SQLException
     */
    public fMahasiswa() throws SQLException {
        initComponents();
        tmhs.setModel(dtm);
        dtm.addColumn("Nama Mahasiswa");
        dtm.addColumn("NIM");
        dtm.addColumn("Jenis Kelamin");
        dtm.addColumn("Program studi");
        
        lsDtMhs();
        
        fieldEnabled(false);
        tombol(false);
         cBaru.setEnabled(true);
         cTutup.setEnabled(true);
         cHapus.setEnabled(true);
         cUbah.setEnabled(true);
         
        
        
    }
    private void fieldEnabled(boolean opsi) {
    txnim.setEditable(opsi);
     txnama.setEditable(opsi);
     txJK.setEditable(opsi);
     txprodi.setEditable(opsi);
    }
    private void tombol(boolean opsi){
    cBaru.setEnabled(opsi);
    cHapus.setEnabled(opsi);
    cUbah.setEnabled(opsi);
    cTutup.setEnabled(opsi);
   
    }
    private void clearForm(){
    txnim.setText("");
    txnama.setText("");
    txprodi.setText("");
    txJK.setText("");
   
    }
    private void lsDtMhs() throws SQLException{
        Connection cnn = koneksi();
        dtm.getDataVector().removeAllElements();
        dtm.fireTableDataChanged();
        
        if( !cnn.isClosed()){
            PreparedStatement ps = cnn.prepareStatement("SELECT * FROM mhs;");
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                Object[] dta = new Object[4];
                dta[0] = rs.getString("nama");
                dta[1] = rs.getString("NIM");
                dta[2] = rs.getString("JENIS_KELAMIN");
                dta[3] = rs.getString("PRODI");
                
            dtm.addRow(dta);
            }
            cnn.close();
        }
    }
    
    private void storeData() throws SQLException{
    Connection cnn = koneksi ();
    if(!cnn.isClosed()){
       PreparedStatement ps = cnn.prepareStatement("INSERT INTO mhs(nama,NIM,PRODI,JENIS_KELAMIN) VALUES(?,?,?,?);");
       ps.setString(1,txnama.getText());
       ps.setString(2,txnim.getText());
       ps.setString(3,txprodi.getText());
       ps.setString(4,txJK.getText());
       ps.executeUpdate();
       
        cnn.close();
    }
    }
    private void Updatedata()throws SQLException{
      Connection cnn = koneksi ();
    if(!cnn.isClosed()){
       PreparedStatement ps = cnn.prepareStatement("UPDATE mhs SET nama=?,PRODI=?,JENIS_KELAMIN=? WHERE NIM=?;");
       ps.setString(1,txnama.getText());
       ps.setString(2,txprodi.getText());
       ps.setString(3,txJK.getText());
       ps.setString(4,txnim.getText());
       ps.executeUpdate();
       
        cnn.close();
    }
    }
    private void Destroydata()throws SQLException{
     Connection cnn = koneksi ();
    if(!cnn.isClosed()){
       PreparedStatement ps = cnn.prepareStatement("delete from mhs WHERE NIM=?;");
       ps.setString(1,txnim.getText());
       ps.executeUpdate();
       
        cnn.close();
    }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txnim = new javax.swing.JTextField();
        txnama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txJK = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txprodi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tmhs = new javax.swing.JTable();
        cBaru = new javax.swing.JButton();
        cTutup = new javax.swing.JButton();
        cHapus = new javax.swing.JButton();
        cUbah = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setBackground(new java.awt.Color(255, 51, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Data Mahasiswa");

        jLabel2.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        jLabel2.setText("NIM");

        jLabel3.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        jLabel3.setText("Nama Mhs");

        txnim.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txnim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txnimActionPerformed(evt);
            }
        });

        txnama.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        jLabel4.setText("Jenis Kelamin");

        txJK.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        jLabel5.setText("Program Studi");

        txprodi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        tmhs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tmhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tmhsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tmhs);

        cBaru.setFont(new java.awt.Font("Sitka Display", 0, 14)); // NOI18N
        cBaru.setText("Baru");
        cBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBaruActionPerformed(evt);
            }
        });

        cTutup.setFont(new java.awt.Font("Sitka Display", 0, 14)); // NOI18N
        cTutup.setText("Tutup");
        cTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cTutupActionPerformed(evt);
            }
        });

        cHapus.setFont(new java.awt.Font("Sitka Display", 0, 14)); // NOI18N
        cHapus.setText("Hapus");
        cHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cHapusActionPerformed(evt);
            }
        });

        cUbah.setFont(new java.awt.Font("Sitka Display", 0, 14)); // NOI18N
        cUbah.setText("Ubah");
        cUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cUbahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(txnim)
                    .addComponent(txnama, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txprodi, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txJK, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cBaru, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cTutup, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txnim, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txnama, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txJK, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txprodi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cBaru, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cTutup, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(153, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txnimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txnimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txnimActionPerformed

    private void cHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cHapusActionPerformed
        
        int jwb = JOptionPane.showOptionDialog(
                this,
                "Yakin akan menghapus data "+txnim.getText()+"?", 
               " Konfirmasi hapus data", 
                JOptionPane.YES_NO_OPTION, 
                JOptionPane.QUESTION_MESSAGE,
                null, null, null);
        
        if(jwb == JOptionPane.YES_OPTION ){
            
            }
            try {
                 Destroydata();
                 lsDtMhs();
                 clearForm();
                 cUbah.setEnabled(false);
                 cHapus.setEnabled(false);
             } catch (SQLException ex) {
                 Logger.getLogger(fMahasiswa.class.getName()).log(Level.SEVERE, null, ex);
             } 

    }//GEN-LAST:event_cHapusActionPerformed

    private void cBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBaruActionPerformed
            if(cBaru.getText().equals("Baru")){
            cBaru.setText("simpan");
            cTutup.setText("batal");
            cHapus.setEnabled(false);
            cUbah.setEnabled(false);
            clearForm();
                fieldEnabled(true);
            }else{
                if (!txnim.getText().equals("")){
                    try {
                        storeData();
                        lsDtMhs();
                    } catch (SQLException ex) {
                        Logger.getLogger(fMahasiswa.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            cBaru.setText("Baru");
            cTutup.setText("Tutup");
             clearForm();
                fieldEnabled(false);
            }
    }//GEN-LAST:event_cBaruActionPerformed

    private void cUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cUbahActionPerformed
        
        if(cUbah.getText().equals("Ubah")){
            cUbah.setText("Simpan");
            cTutup.setText("Batal");
            
            cBaru.setEnabled(false);
            cHapus.setEnabled(false);
            fieldEnabled(true);
            txnim.setEditable(false);
                    
        }else{
            
            try {
                Updatedata();
                lsDtMhs();
                clearForm();
                fieldEnabled(false);
                
                cUbah.setText("Ubah");
                cTutup.setText("Tutup");
                cBaru.setEnabled(true);
            } catch (SQLException ex) {
                Logger.getLogger(fMahasiswa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_cUbahActionPerformed

    private void cTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cTutupActionPerformed
        if(cTutup.getText().equals("Tutup")){
        
        int opsi = JOptionPane.showOptionDialog(this, "yakin nih mau nutup form??","konfir duluu", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, null,null);
        if(opsi == JOptionPane.YES_OPTION){
        System.exit(0);}
        }else{
            cTutup.setText("Tutup");
            cBaru.setText("Baru");
            cUbah.setText("Ubah");
            
            fieldEnabled(false);
        }
    }//GEN-LAST:event_cTutupActionPerformed

    private void tmhsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tmhsMouseClicked
        txnim.setText(tmhs.getValueAt(tmhs.getSelectedRow(), 1).toString()  );
        txnama.setText(tmhs.getValueAt(tmhs.getSelectedRow(), 0).toString()  );
        txprodi.setText(tmhs.getValueAt(tmhs.getSelectedRow(), 3).toString()  );
        String jkx =(tmhs.getValueAt(tmhs.getSelectedRow(), 2).toString().equals("L"))?"laki-laki":"perempuan";
        txJK.setText(jkx);
        cHapus.setEnabled(true);
        cUbah.setEnabled(true);

    }//GEN-LAST:event_tmhsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new fMahasiswa().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(fMahasiswa.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cBaru;
    private javax.swing.JButton cHapus;
    private javax.swing.JButton cTutup;
    private javax.swing.JButton cUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tmhs;
    private javax.swing.JTextField txJK;
    private javax.swing.JTextField txnama;
    private javax.swing.JTextField txnim;
    private javax.swing.JTextField txprodi;
    // End of variables declaration//GEN-END:variables

 
}
